import type { Prisma } from '@prisma/client';

/** Shape accepted when auto-registering a customer from another module's form. */
export interface NewCustomerInput {
  customerType?: string;
  title?: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  phone: string;
  email?: string;
  address: string;
  city?: string;
  state?: string;
  dateOfBirth?: string;
  gender?: string;
  occupation?: string;
  employer?: string;
  monthlyIncome?: number;
  bvn?: string;
  nationalId?: string;
  nokName?: string;
  nokRelationship?: string;
  nokPhone?: string;
  nokAddress?: string;
  companyName?: string;
  rcNumber?: string;
}

/** Validate the minimum fields required to register a new customer. */
export function validateNewCustomer(nc: NewCustomerInput): string | null {
  if (!nc.firstName?.trim() || !nc.lastName?.trim()) return 'New customer requires first and last name';
  if (!nc.phone?.trim()) return 'New customer requires a phone number';
  if (!nc.address?.trim()) return 'New customer requires an address';
  return null;
}

/**
 * Create a customer inside an existing transaction. The customerNumber must be
 * generated by the caller BEFORE opening the transaction (generateReference
 * runs its own query and should not be nested).
 */
export async function createCustomerInTx(
  tx: Prisma.TransactionClient,
  nc: NewCustomerInput,
  ctx: { customerNumber: string; branchId: string; createdBy: string }
) {
  return tx.customer.create({
    data: {
      customerNumber: ctx.customerNumber,
      customerType: (nc.customerType as never) || 'INDIVIDUAL',
      title: nc.title,
      firstName: nc.firstName.trim(),
      lastName: nc.lastName.trim(),
      middleName: nc.middleName,
      phone: nc.phone.trim(),
      email: nc.email || undefined,
      address: nc.address.trim(),
      city: nc.city,
      state: nc.state,
      dateOfBirth: nc.dateOfBirth ? new Date(nc.dateOfBirth) : undefined,
      gender: nc.gender,
      occupation: nc.occupation,
      employer: nc.employer,
      monthlyIncome: nc.monthlyIncome,
      bvn: nc.bvn,
      nationalId: nc.nationalId,
      nokName: nc.nokName,
      nokRelationship: nc.nokRelationship,
      nokPhone: nc.nokPhone,
      nokAddress: nc.nokAddress,
      companyName: nc.companyName,
      rcNumber: nc.rcNumber,
      branchId: ctx.branchId,
      createdBy: ctx.createdBy,
    },
  });
}
