/**
 * ESLint flat config.
 *
 * This replaces `.eslintrc.json`, which did not merely misbehave — it crashed
 * ESLint on every run with "Converting circular structure to JSON".
 *
 * The cause: `eslint-config-next` v16 ships *only* flat-config exports and
 * requires eslint >= 9, while this project was on eslint 8 with a legacy
 * eslintrc file. `extends: "next/core-web-vitals"` therefore handed an array of
 * flat config objects to the old eslintrc validator, which rejected it — and
 * then crashed trying to `JSON.stringify` the offending config to format the
 * error message, because eslint-plugin-react self-references through
 * `configs.flat.plugins.react`. The circular-JSON error was the error formatter
 * dying; the real complaint was never printed.
 *
 * Scope: `eslint-config-next/core-web-vitals` already carries the TypeScript
 * parser (its `next/typescript` entry), all five plugins, and ignores for build
 * output. The separate `eslint-config-next/typescript` export is the full
 * typescript-eslint *recommended* rule set — far stricter than anything this
 * codebase has been linted against, so it is deliberately left out. Adding it
 * is a decision about the code, not a fix to the config.
 */

import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';

// Named rather than exported anonymously, so this file passes the very rule
// set it installs (import/no-anonymous-default-export).
const config = [
  ...nextCoreWebVitals,
  {
    // Flat config does not read .eslintignore, so anything not covered by the
    // ignores bundled in core-web-vitals (.next, out, build, next-env.d.ts)
    // belongs here.
    ignores: [
      'public/sw.js', // generated by serwist at build time — a minified bundle
      'coverage/**',
      '.vercel/**',
    ],
  },
];

export default config;
